# Generated by Django 4.2.5 on 2023-09-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='codigo',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
