# Generated by Django 4.2.5 on 2023-09-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPromocion', models.CharField(max_length=20)),
                ('codigo', models.CharField(editable=False, max_length=8, unique=True)),
                ('fecha_de_validez', models.DateTimeField()),
                ('username', models.CharField(max_length=255)),
            ],
        ),
    ]
