# Generated by Django 4.2.5 on 2023-09-20 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigo',
            name='fecha_de_validez',
        ),
    ]
