# Generated by Django 4.2.5 on 2023-09-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20)),
                ('usuario', models.CharField(editable=False, max_length=8, unique=True)),
                ('fecha_canje', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
