# Generated by Django 4.2.5 on 2023-09-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historicoCodigos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcodigo',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
    ]
